package ru.geekbrains.pictureapp.presentation.ui.common;

public enum NotifyingMessage {

    PHOTO_SUCCESSFULLY_ADDED,
    PHOTO_SUCCESSFULLY_DELETED,
    PHOTO_SUCCESSFULLY_DELETED_FROM_FAVORITES,
    PHOTO_SUCCESSFULLY_DELETED_FROM_DEVICE,
    ERROR_ADD_PHOTO_TO_FAVORITES,
    ERROR_DELETE_PHOTO,
    ERROR_DELETE_PHOTO_FROM_FAVORITES,
    ERROR_DELETE_PHOTO_FROM_DEVICE,
    ERROR_CAMERA_OPEN,
    ERROR_LOAD_PHOTO
}
